# Generated by Django 5.2.7 on 2025-10-16 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='PcProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=200)),
                ('mother_board', models.CharField(max_length=200)),
                ('gpu', models.CharField(max_length=200)),
                ('power_block', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('ssd', models.CharField(blank=True, max_length=200, null=True)),
                ('hdd', models.CharField(blank=True, max_length=200, null=True)),
                ('adapters', models.CharField(blank=True, max_length=250, null=True)),
                ('coolers', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_details', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='MouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('is_wireless', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse_details', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=200)),
                ('mother_board', models.CharField(max_length=200)),
                ('gpu', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('ssd', models.CharField(blank=True, max_length=200, null=True)),
                ('hdd', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charger', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=200)),
                ('web_cam', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_details', to='catalog.product')),
            ],
        ),
    ]
